matrix:
  include:
  - name: Ubuntu Bionic (18.04) (Docker) with Python 3.6
    env:
    - MODE="pypi"
    - UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
cache:
- pip
install:
- ./config/travis/install.sh
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
