version: ~> 1.0
language: generic
os: linux
dist: bionic
jobs:
  include:
  - name: Ubuntu Focal (20.04) (Docker) with Python 3.8 using GIFT PPA
    env: UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: Ubuntu Focal (20.04) (Docker) with Python 3.8 using PyPI
    env:
    - TARGET="pypi"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: Ubuntu Focal (20.04) (Docker) with Python 3.7 (tox)
    env:
    - TOXENV="py37"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: Ubuntu Focal (20.04) (Docker) with Python 3.8 (tox)
    env:
    - TOXENV="py38"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: Pylint on Ubuntu Focal (20.04) (Docker) with Python 3.8 (tox)
    env:
    - TOXENV="pylint"
    - UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: Dockerfile-prod
    env: TARGET="dockerfile"
    group: edge
cache:
- pip
install:
- ./config/travis/install.sh
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
